### ISSUE TITLE
how to support the RNN

### ISSUE THREAD

**Issue by justdark** [lantiga/pytorch2c#1]
the way you traverse the Graph can't recognise the loops in RNN layers.
so the graph will become super complicated even exceed the maxium recursive dept of Python.
Although I can set the depth to a big number and finally export a graph with more than 7000 functions(input with 400 length series  for LSTM),I think this graph is too redundant to use.

but do recursive to the creator of node can't really know the existence of LSTM layer, any idea about it?

**Comment by lantiga** [comment]
I didn't get notified about this for some reason.
This is a common issue that I would definitely like to resolve. Can you post a minimal sample, to speed things up?

**Comment by lantiga** [comment]
Closing since this will be taken care of by the JIT engine.
